// Generated by https://quicktype.io

import { IPedido } from "./IPedido";

export interface IOrders {
  id: string;
  name: string;
  email: string;
  phone: number;
  country: string;
  address: string;
  city: string;
  orders: Order[];
}

export interface Order {
  id: string;
  date: string;
  orderDetails: OrderDetails;
}

export interface OrderDetails {
  id: string;
  price: string;
  products: Product[];
  statushistory: Statushistory[];
}

export interface Product {
  id: string;
  name: string;
  description: string;
  price: string;
  stock: number;
  imgUrl: string;
  discount: string;
  size: string;
}

export interface Statushistory {
  id: string;
  status: string;
  timestamp: string;
}
