// Generated by https://quicktype.io

export interface IUsers {
  id: string;
  name: string;
  email: string;
  isAdmin: boolean;
  isSuperAdmin: boolean;
  condition: boolean;
  phone: number;
  country: string;
  address: string;
  city: string;
}
