// import React from "react";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/navbar/Navbar";
// import { ThemeModeScript } from "flowbite-react";
// import Provider from "@/context/Provider";
// import Footer from "@/components/footer/Footer";
// import { PayPalContext } from "@/context/PayPalContext";
// import { CategoryProvider } from "@/context/category.context";
// import Chatbot from "@/components/Chatbot/Chatbot";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Fast Burgers",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <ThemeModeScript />
//       </head>
//       <body className={inter.className}>
//         <CategoryProvider>
//           <PayPalContext>
//             <Provider>
//               <Navbar />
//               {children}
//               <Chatbot/>
//               <Footer />
//             </Provider>
//           </PayPalContext>
//         </CategoryProvider>
//       </body>
//     </html>
//   );
// }

import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Provider from "@/context/Provider";
import { PayPalContext } from "@/context/PayPalContext";
import { CategoryProvider } from "@/context/category.context";
import IsAdminWrapper from "@/components/IsAdminWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fast Burgers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <CategoryProvider>
          <PayPalContext>
            <Provider>
              <IsAdminWrapper>{children}</IsAdminWrapper>
            </Provider>
          </PayPalContext>
        </CategoryProvider>
      </body>
    </html>
  );
}

// import React from "react";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeModeScript } from "flowbite-react";
// import Provider from "@/context/Provider";
// import { PayPalContext } from "@/context/PayPalContext";
// import { CategoryProvider } from "@/context/category.context";
// import ClientWrapper from "@/components/ClientWrapper";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Fast Burgers",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <ThemeModeScript />
//       </head>
//       <body className={inter.className}>
//         <CategoryProvider>
//           <PayPalContext>
//             <Provider>
//               <ClientWrapper>{children}</ClientWrapper>
//             </Provider>
//           </PayPalContext>
//         </CategoryProvider>
//       </body>
//     </html>
//   );
// }
